import { describe, it, expect } from "vitest";
import { addManipulator } from "./manipulation";
import { loadWithDefaults } from "./jif_loader";
import { prechacToJif, parseManipulator } from "./high_level_converter";
import {
  RAW_DATA_WALKING_FEED_9C,
  RAW_DATA_WALKING_FEED_10C,
} from "./test_data";

const RAW_PHOENICIAN_WALTZ = [
  "3B 3B  3  3B 3B  3  3B 3B  3",
  "3A 3A  3  3A 3A  3  3A 3A  3",
];

describe("addManipulator", () => {
  it("adds manipulator to Phoenician Waltz", () => {
    const jif = loadWithDefaults(prechacToJif(RAW_PHOENICIAN_WALTZ));
    const manipulator = parseManipulator("sA - - sA - - i1A - -");
    const result = addManipulator(jif, manipulator);
    expect(result).toMatchInlineSnapshot(`
      {
        "jugglers": [
          {
            "becomes": 1,
            "label": "A",
          },
          {
            "becomes": 2,
            "label": "B",
          },
          {
            "becomes": 0,
            "label": "M",
          },
        ],
        "limbs": [
          {
            "juggler": 0,
            "kind": "right_hand",
            "label": "R",
            "type": "right hand",
          },
          {
            "juggler": 0,
            "kind": "left_hand",
            "label": "L",
            "type": "left hand",
          },
          {
            "juggler": 1,
            "kind": "right_hand",
            "label": "R",
            "type": "right hand",
          },
          {
            "juggler": 1,
            "kind": "left_hand",
            "label": "L",
            "type": "left hand",
          },
          {
            "juggler": 2,
            "kind": "right_hand",
            "label": "R",
            "type": "right hand",
          },
          {
            "juggler": 2,
            "kind": "left_hand",
            "label": "L",
            "type": "left hand",
          },
        ],
        "objects": [],
        "repetition": {
          "limbPermutation": [
            3,
            2,
            5,
            4,
            1,
            0,
          ],
          "period": 9,
        },
        "throws": [
          {
            "duration": 1,
            "from": 0,
            "isManipulated": true,
            "time": 0,
            "to": 5,
          },
          {
            "duration": 3,
            "from": 1,
            "isManipulated": false,
            "time": 1,
            "to": 2,
          },
          {
            "duration": 3,
            "from": 0,
            "isManipulated": false,
            "time": 2,
            "to": 1,
          },
          {
            "duration": 1,
            "from": 1,
            "isManipulated": true,
            "time": 3,
            "to": 4,
          },
          {
            "duration": 3,
            "from": 0,
            "isManipulated": false,
            "time": 4,
            "to": 3,
          },
          {
            "duration": 3,
            "from": 1,
            "isManipulated": false,
            "time": 5,
            "to": 0,
          },
          {
            "duration": 3,
            "from": 0,
            "isManipulated": true,
            "time": 6,
            "to": 5,
          },
          {
            "duration": 3,
            "from": 1,
            "isManipulated": false,
            "time": 7,
            "to": 4,
          },
          {
            "duration": 3,
            "from": 0,
            "isManipulated": false,
            "time": 8,
            "to": 1,
          },
          {
            "duration": 3,
            "from": 2,
            "isManipulated": false,
            "time": 0,
            "to": 1,
          },
          {
            "duration": 3,
            "from": 3,
            "isManipulated": false,
            "time": 1,
            "to": 0,
          },
          {
            "duration": 3,
            "from": 2,
            "isManipulated": false,
            "time": 2,
            "to": 3,
          },
          {
            "duration": 3,
            "from": 3,
            "isManipulated": false,
            "time": 3,
            "to": 0,
          },
          {
            "duration": 3,
            "from": 2,
            "isManipulated": false,
            "time": 4,
            "to": 1,
          },
          {
            "duration": 3,
            "from": 3,
            "isManipulated": false,
            "time": 5,
            "to": 2,
          },
          {
            "duration": 3,
            "from": 2,
            "isManipulated": false,
            "time": 6,
            "to": 1,
          },
          {
            "duration": 3,
            "from": 3,
            "isManipulated": true,
            "time": 7,
            "to": 0,
          },
          {
            "duration": 3,
            "from": 4,
            "isManipulated": false,
            "time": 8,
            "to": 5,
          },
          {
            "duration": 1,
            "from": 4,
            "isManipulated": false,
            "time": 6,
            "to": 5,
          },
          {
            "duration": 1,
            "from": 5,
            "isManipulated": false,
            "time": 7,
            "to": 4,
          },
          {
            "duration": 1,
            "from": 2,
            "isManipulated": false,
            "time": 8,
            "to": 3,
          },
          {
            "duration": 3,
            "from": 4,
            "isManipulated": true,
            "time": 0,
            "to": 3,
          },
          {
            "duration": 1,
            "from": 5,
            "isManipulated": false,
            "time": 1,
            "to": 4,
          },
          {
            "duration": 1,
            "from": 4,
            "isManipulated": false,
            "time": 2,
            "to": 5,
          },
          {
            "duration": 3,
            "from": 5,
            "isManipulated": true,
            "time": 3,
            "to": 2,
          },
          {
            "duration": 1,
            "from": 4,
            "isManipulated": false,
            "time": 4,
            "to": 5,
          },
          {
            "duration": 1,
            "from": 5,
            "isManipulated": false,
            "time": 5,
            "to": 4,
          },
        ],
      }
    `);
  });

  it("adds three manipulators to Göttinger Opernball", () => {
    const baseJif = loadWithDefaults(prechacToJif(RAW_PHOENICIAN_WALTZ));
    const manipulators = [
      "sA - - sA - - i1A - -",
      "sB - - i1B - - sA - -",
      "i1A - - sB - - sB - -",
    ];

    let jif = baseJif;
    for (const m of manipulators) {
      jif = addManipulator(jif, parseManipulator(m));
    }

    expect(jif).toMatchInlineSnapshot(`
      {
        "jugglers": [
          {
            "becomes": 3,
            "label": "A",
          },
          {
            "becomes": 2,
            "label": "B",
          },
          {
            "becomes": 4,
            "label": "M1",
          },
          {
            "becomes": 1,
            "label": "M2",
          },
          {
            "becomes": 0,
            "label": "M3",
          },
        ],
        "limbs": [
          {
            "juggler": 0,
            "kind": "right_hand",
            "label": "R",
            "type": "right hand",
          },
          {
            "juggler": 0,
            "kind": "left_hand",
            "label": "L",
            "type": "left hand",
          },
          {
            "juggler": 1,
            "kind": "right_hand",
            "label": "R",
            "type": "right hand",
          },
          {
            "juggler": 1,
            "kind": "left_hand",
            "label": "L",
            "type": "left hand",
          },
          {
            "juggler": 2,
            "kind": "right_hand",
            "label": "R",
            "type": "right hand",
          },
          {
            "juggler": 2,
            "kind": "left_hand",
            "label": "L",
            "type": "left hand",
          },
          {
            "juggler": 3,
            "kind": "right_hand",
            "label": "R",
            "type": "right hand",
          },
          {
            "juggler": 3,
            "kind": "left_hand",
            "label": "L",
            "type": "left hand",
          },
          {
            "juggler": 4,
            "kind": "right_hand",
            "label": "R",
            "type": "right hand",
          },
          {
            "juggler": 4,
            "kind": "left_hand",
            "label": "L",
            "type": "left hand",
          },
        ],
        "objects": [],
        "repetition": {
          "limbPermutation": [
            7,
            6,
            5,
            4,
            9,
            8,
            3,
            2,
            1,
            0,
          ],
          "period": 9,
        },
        "throws": [
          {
            "duration": 1,
            "from": 0,
            "isManipulated": true,
            "time": 0,
            "to": 9,
          },
          {
            "duration": 3,
            "from": 1,
            "isManipulated": false,
            "time": 1,
            "to": 2,
          },
          {
            "duration": 3,
            "from": 0,
            "isManipulated": false,
            "time": 2,
            "to": 1,
          },
          {
            "duration": 1,
            "from": 1,
            "isManipulated": true,
            "time": 3,
            "to": 8,
          },
          {
            "duration": 3,
            "from": 0,
            "isManipulated": true,
            "time": 4,
            "to": 3,
          },
          {
            "duration": 3,
            "from": 7,
            "isManipulated": false,
            "time": 5,
            "to": 6,
          },
          {
            "duration": 1,
            "from": 6,
            "isManipulated": true,
            "time": 6,
            "to": 1,
          },
          {
            "duration": 3,
            "from": 7,
            "isManipulated": false,
            "time": 7,
            "to": 8,
          },
          {
            "duration": 3,
            "from": 6,
            "isManipulated": false,
            "time": 8,
            "to": 7,
          },
          {
            "duration": 1,
            "from": 2,
            "isManipulated": true,
            "time": 0,
            "to": 7,
          },
          {
            "duration": 3,
            "from": 3,
            "isManipulated": false,
            "time": 1,
            "to": 0,
          },
          {
            "duration": 3,
            "from": 2,
            "isManipulated": false,
            "time": 2,
            "to": 3,
          },
          {
            "duration": 1,
            "from": 3,
            "isManipulated": true,
            "time": 3,
            "to": 4,
          },
          {
            "duration": 3,
            "from": 2,
            "isManipulated": false,
            "time": 4,
            "to": 7,
          },
          {
            "duration": 3,
            "from": 3,
            "isManipulated": false,
            "time": 5,
            "to": 2,
          },
          {
            "duration": 1,
            "from": 2,
            "isManipulated": true,
            "time": 6,
            "to": 5,
          },
          {
            "duration": 3,
            "from": 3,
            "isManipulated": true,
            "time": 7,
            "to": 6,
          },
          {
            "duration": 3,
            "from": 8,
            "isManipulated": false,
            "time": 8,
            "to": 9,
          },
          {
            "duration": 1,
            "from": 8,
            "isManipulated": false,
            "time": 6,
            "to": 9,
          },
          {
            "duration": 1,
            "from": 9,
            "isManipulated": false,
            "time": 7,
            "to": 8,
          },
          {
            "duration": 1,
            "from": 2,
            "isManipulated": false,
            "time": 8,
            "to": 3,
          },
          {
            "duration": 3,
            "from": 8,
            "isManipulated": true,
            "time": 0,
            "to": 3,
          },
          {
            "duration": 1,
            "from": 9,
            "isManipulated": false,
            "time": 1,
            "to": 8,
          },
          {
            "duration": 1,
            "from": 8,
            "isManipulated": false,
            "time": 2,
            "to": 9,
          },
          {
            "duration": 3,
            "from": 9,
            "isManipulated": true,
            "time": 3,
            "to": 2,
          },
          {
            "duration": 1,
            "from": 8,
            "isManipulated": false,
            "time": 4,
            "to": 9,
          },
          {
            "duration": 1,
            "from": 9,
            "isManipulated": false,
            "time": 5,
            "to": 8,
          },
          {
            "duration": 1,
            "from": 7,
            "isManipulated": false,
            "time": 3,
            "to": 6,
          },
          {
            "duration": 1,
            "from": 6,
            "isManipulated": false,
            "time": 4,
            "to": 7,
          },
          {
            "duration": 1,
            "from": 1,
            "isManipulated": false,
            "time": 5,
            "to": 0,
          },
          {
            "duration": 3,
            "from": 0,
            "isManipulated": true,
            "time": 6,
            "to": 9,
          },
          {
            "duration": 1,
            "from": 1,
            "isManipulated": false,
            "time": 7,
            "to": 0,
          },
          {
            "duration": 1,
            "from": 0,
            "isManipulated": false,
            "time": 8,
            "to": 1,
          },
          {
            "duration": 3,
            "from": 6,
            "isManipulated": true,
            "time": 0,
            "to": 1,
          },
          {
            "duration": 1,
            "from": 7,
            "isManipulated": false,
            "time": 1,
            "to": 6,
          },
          {
            "duration": 1,
            "from": 6,
            "isManipulated": false,
            "time": 2,
            "to": 7,
          },
          {
            "duration": 1,
            "from": 4,
            "isManipulated": false,
            "time": 0,
            "to": 5,
          },
          {
            "duration": 1,
            "from": 5,
            "isManipulated": false,
            "time": 1,
            "to": 4,
          },
          {
            "duration": 1,
            "from": 4,
            "isManipulated": false,
            "time": 2,
            "to": 5,
          },
          {
            "duration": 3,
            "from": 5,
            "isManipulated": true,
            "time": 3,
            "to": 6,
          },
          {
            "duration": 1,
            "from": 4,
            "isManipulated": false,
            "time": 4,
            "to": 5,
          },
          {
            "duration": 1,
            "from": 5,
            "isManipulated": false,
            "time": 5,
            "to": 4,
          },
          {
            "duration": 3,
            "from": 4,
            "isManipulated": true,
            "time": 6,
            "to": 7,
          },
          {
            "duration": 1,
            "from": 5,
            "isManipulated": false,
            "time": 7,
            "to": 4,
          },
          {
            "duration": 1,
            "from": 4,
            "isManipulated": false,
            "time": 8,
            "to": 5,
          },
        ],
      }
    `);
  });

  it("adds manipulator to Scrambled B", () => {
    const jif = loadWithDefaults(prechacToJif(RAW_DATA_WALKING_FEED_9C));
    const manipulator = parseManipulator("i2A - - - sB -");
    const result = addManipulator(jif, manipulator);
    expect(result).toMatchInlineSnapshot(`
      {
        "jugglers": [
          {
            "becomes": 1,
            "label": "A",
          },
          {
            "becomes": 3,
            "label": "B",
          },
          {
            "becomes": 0,
            "label": "C",
          },
          {
            "becomes": 2,
            "label": "M",
          },
        ],
        "limbs": [
          {
            "juggler": 0,
            "kind": "right_hand",
            "label": "R",
            "type": "right hand",
          },
          {
            "juggler": 0,
            "kind": "left_hand",
            "label": "L",
            "type": "left hand",
          },
          {
            "juggler": 1,
            "kind": "right_hand",
            "label": "R",
            "type": "right hand",
          },
          {
            "juggler": 1,
            "kind": "left_hand",
            "label": "L",
            "type": "left hand",
          },
          {
            "juggler": 2,
            "kind": "right_hand",
            "label": "R",
            "type": "right hand",
          },
          {
            "juggler": 2,
            "kind": "left_hand",
            "label": "L",
            "type": "left hand",
          },
          {
            "juggler": 3,
            "kind": "right_hand",
            "label": "R",
            "type": "right hand",
          },
          {
            "juggler": 3,
            "kind": "left_hand",
            "label": "L",
            "type": "left hand",
          },
        ],
        "objects": [],
        "repetition": {
          "limbPermutation": [
            2,
            3,
            6,
            7,
            0,
            1,
            4,
            5,
          ],
          "period": 6,
        },
        "throws": [
          {
            "duration": 3,
            "from": 0,
            "isManipulated": true,
            "time": 0,
            "to": 7,
          },
          {
            "duration": 3,
            "from": 1,
            "isManipulated": false,
            "time": 1,
            "to": 0,
          },
          {
            "duration": 3,
            "from": 0,
            "isManipulated": false,
            "time": 2,
            "to": 5,
          },
          {
            "duration": 3,
            "from": 1,
            "isManipulated": false,
            "time": 3,
            "to": 0,
          },
          {
            "duration": 3,
            "from": 0,
            "isManipulated": false,
            "time": 4,
            "to": 7,
          },
          {
            "duration": 3,
            "from": 1,
            "isManipulated": false,
            "time": 5,
            "to": 0,
          },
          {
            "duration": 3,
            "from": 2,
            "isManipulated": false,
            "time": 0,
            "to": 1,
          },
          {
            "duration": 2,
            "from": 6,
            "isManipulated": false,
            "time": 2,
            "to": 6,
          },
          {
            "duration": 3,
            "from": 2,
            "isManipulated": true,
            "time": 2,
            "to": 7,
          },
          {
            "duration": 3,
            "from": 7,
            "isManipulated": false,
            "time": 3,
            "to": 6,
          },
          {
            "duration": 1,
            "from": 6,
            "isManipulated": true,
            "time": 4,
            "to": 3,
          },
          {
            "duration": 3,
            "from": 7,
            "isManipulated": false,
            "time": 5,
            "to": 6,
          },
          {
            "duration": 3,
            "from": 4,
            "isManipulated": false,
            "time": 0,
            "to": 5,
          },
          {
            "duration": 3,
            "from": 5,
            "isManipulated": false,
            "time": 1,
            "to": 4,
          },
          {
            "duration": 3,
            "from": 4,
            "isManipulated": false,
            "time": 2,
            "to": 1,
          },
          {
            "duration": 3,
            "from": 5,
            "isManipulated": false,
            "time": 3,
            "to": 4,
          },
          {
            "duration": 3,
            "from": 4,
            "isManipulated": false,
            "time": 4,
            "to": 5,
          },
          {
            "duration": 3,
            "from": 5,
            "isManipulated": false,
            "time": 5,
            "to": 4,
          },
          {
            "duration": 2,
            "from": 3,
            "isManipulated": false,
            "time": 1,
            "to": 3,
          },
          {
            "duration": 1,
            "from": 6,
            "isManipulated": false,
            "time": 0,
            "to": 7,
          },
          {
            "duration": 1,
            "from": 7,
            "isManipulated": false,
            "time": 1,
            "to": 6,
          },
          {
            "duration": 1,
            "from": 3,
            "isManipulated": false,
            "time": 3,
            "to": 2,
          },
          {
            "duration": 3,
            "from": 2,
            "isManipulated": true,
            "time": 4,
            "to": 1,
          },
          {
            "duration": 1,
            "from": 3,
            "isManipulated": false,
            "time": 5,
            "to": 2,
          },
        ],
      }
    `);
  });

  it("adds manipulator to Toast", () => {
    const jif = loadWithDefaults(prechacToJif(RAW_DATA_WALKING_FEED_9C));
    const manipulator = parseManipulator("sA - i2A - - -");
    const result = addManipulator(jif, manipulator);
    expect(result).toMatchInlineSnapshot(`
      {
        "jugglers": [
          {
            "becomes": 1,
            "label": "A",
          },
          {
            "becomes": 2,
            "label": "B",
          },
          {
            "becomes": 3,
            "label": "C",
          },
          {
            "becomes": 0,
            "label": "M",
          },
        ],
        "limbs": [
          {
            "juggler": 0,
            "kind": "right_hand",
            "label": "R",
            "type": "right hand",
          },
          {
            "juggler": 0,
            "kind": "left_hand",
            "label": "L",
            "type": "left hand",
          },
          {
            "juggler": 1,
            "kind": "right_hand",
            "label": "R",
            "type": "right hand",
          },
          {
            "juggler": 1,
            "kind": "left_hand",
            "label": "L",
            "type": "left hand",
          },
          {
            "juggler": 2,
            "kind": "right_hand",
            "label": "R",
            "type": "right hand",
          },
          {
            "juggler": 2,
            "kind": "left_hand",
            "label": "L",
            "type": "left hand",
          },
          {
            "juggler": 3,
            "kind": "right_hand",
            "label": "R",
            "type": "right hand",
          },
          {
            "juggler": 3,
            "kind": "left_hand",
            "label": "L",
            "type": "left hand",
          },
        ],
        "objects": [],
        "repetition": {
          "limbPermutation": [
            2,
            3,
            4,
            5,
            6,
            7,
            0,
            1,
          ],
          "period": 6,
        },
        "throws": [
          {
            "duration": 1,
            "from": 0,
            "isManipulated": true,
            "time": 0,
            "to": 7,
          },
          {
            "duration": 3,
            "from": 1,
            "isManipulated": false,
            "time": 1,
            "to": 0,
          },
          {
            "duration": 3,
            "from": 0,
            "isManipulated": true,
            "time": 2,
            "to": 7,
          },
          {
            "duration": 3,
            "from": 1,
            "isManipulated": false,
            "time": 3,
            "to": 0,
          },
          {
            "duration": 3,
            "from": 0,
            "isManipulated": false,
            "time": 4,
            "to": 3,
          },
          {
            "duration": 3,
            "from": 1,
            "isManipulated": false,
            "time": 5,
            "to": 0,
          },
          {
            "duration": 3,
            "from": 2,
            "isManipulated": false,
            "time": 0,
            "to": 1,
          },
          {
            "duration": 3,
            "from": 3,
            "isManipulated": false,
            "time": 1,
            "to": 2,
          },
          {
            "duration": 3,
            "from": 2,
            "isManipulated": false,
            "time": 2,
            "to": 3,
          },
          {
            "duration": 3,
            "from": 3,
            "isManipulated": false,
            "time": 3,
            "to": 2,
          },
          {
            "duration": 3,
            "from": 2,
            "isManipulated": false,
            "time": 4,
            "to": 1,
          },
          {
            "duration": 3,
            "from": 3,
            "isManipulated": false,
            "time": 5,
            "to": 2,
          },
          {
            "duration": 3,
            "from": 4,
            "isManipulated": false,
            "time": 0,
            "to": 5,
          },
          {
            "duration": 3,
            "from": 5,
            "isManipulated": false,
            "time": 1,
            "to": 4,
          },
          {
            "duration": 3,
            "from": 4,
            "isManipulated": false,
            "time": 2,
            "to": 1,
          },
          {
            "duration": 2,
            "from": 6,
            "isManipulated": false,
            "time": 4,
            "to": 6,
          },
          {
            "duration": 3,
            "from": 4,
            "isManipulated": true,
            "time": 4,
            "to": 7,
          },
          {
            "duration": 3,
            "from": 7,
            "isManipulated": false,
            "time": 5,
            "to": 6,
          },
          {
            "duration": 2,
            "from": 5,
            "isManipulated": false,
            "time": 3,
            "to": 5,
          },
          {
            "duration": 1,
            "from": 6,
            "isManipulated": false,
            "time": 2,
            "to": 7,
          },
          {
            "duration": 1,
            "from": 7,
            "isManipulated": false,
            "time": 3,
            "to": 6,
          },
          {
            "duration": 1,
            "from": 5,
            "isManipulated": false,
            "time": 5,
            "to": 4,
          },
          {
            "duration": 3,
            "from": 6,
            "isManipulated": true,
            "time": 0,
            "to": 3,
          },
          {
            "duration": 1,
            "from": 7,
            "isManipulated": false,
            "time": 1,
            "to": 6,
          },
        ],
      }
    `);
  });

  it("adds manipulator to Choptopus", () => {
    const jif = loadWithDefaults(prechacToJif(RAW_DATA_WALKING_FEED_10C));
    const manipulator = parseManipulator("- sB - i2c - - -");
    const result = addManipulator(jif, manipulator);
    expect(result).toMatchInlineSnapshot(`
      {
        "jugglers": [
          {
            "becomes": 3,
            "label": "A",
          },
          {
            "becomes": 2,
            "label": "B",
          },
          {
            "becomes": 0,
            "label": "C",
          },
          {
            "becomes": 1,
            "label": "M",
          },
        ],
        "limbs": [
          {
            "juggler": 0,
            "kind": "right_hand",
            "label": "R",
            "type": "right hand",
          },
          {
            "juggler": 0,
            "kind": "left_hand",
            "label": "L",
            "type": "left hand",
          },
          {
            "juggler": 1,
            "kind": "right_hand",
            "label": "R",
            "type": "right hand",
          },
          {
            "juggler": 1,
            "kind": "left_hand",
            "label": "L",
            "type": "left hand",
          },
          {
            "juggler": 2,
            "kind": "right_hand",
            "label": "R",
            "type": "right hand",
          },
          {
            "juggler": 2,
            "kind": "left_hand",
            "label": "L",
            "type": "left hand",
          },
          {
            "juggler": 3,
            "kind": "right_hand",
            "label": "R",
            "type": "right hand",
          },
          {
            "juggler": 3,
            "kind": "left_hand",
            "label": "L",
            "type": "left hand",
          },
        ],
        "objects": [],
        "repetition": {
          "limbPermutation": [
            7,
            6,
            5,
            4,
            1,
            0,
            3,
            2,
          ],
          "period": 7,
        },
        "throws": [
          {
            "duration": 4,
            "from": 0,
            "isManipulated": false,
            "time": 0,
            "to": 2,
          },
          {
            "duration": 3,
            "from": 1,
            "isManipulated": false,
            "time": 1,
            "to": 0,
          },
          {
            "duration": 4,
            "from": 0,
            "isManipulated": false,
            "time": 2,
            "to": 4,
          },
          {
            "duration": 3,
            "from": 1,
            "isManipulated": false,
            "time": 3,
            "to": 0,
          },
          {
            "duration": 4,
            "from": 0,
            "isManipulated": false,
            "time": 4,
            "to": 2,
          },
          {
            "duration": 2,
            "from": 6,
            "isManipulated": false,
            "time": 6,
            "to": 6,
          },
          {
            "duration": 4,
            "from": 0,
            "isManipulated": true,
            "time": 6,
            "to": 4,
          },
          {
            "duration": 3,
            "from": 2,
            "isManipulated": false,
            "time": 0,
            "to": 3,
          },
          {
            "duration": 1,
            "from": 3,
            "isManipulated": true,
            "time": 1,
            "to": 6,
          },
          {
            "duration": 3,
            "from": 2,
            "isManipulated": false,
            "time": 2,
            "to": 3,
          },
          {
            "duration": 3,
            "from": 3,
            "isManipulated": false,
            "time": 3,
            "to": 2,
          },
          {
            "duration": 3,
            "from": 2,
            "isManipulated": false,
            "time": 4,
            "to": 3,
          },
          {
            "duration": 4,
            "from": 3,
            "isManipulated": false,
            "time": 5,
            "to": 7,
          },
          {
            "duration": 4,
            "from": 2,
            "isManipulated": false,
            "time": 6,
            "to": 2,
          },
          {
            "duration": 2,
            "from": 4,
            "isManipulated": false,
            "time": 0,
            "to": 4,
          },
          {
            "duration": 3,
            "from": 5,
            "isManipulated": false,
            "time": 1,
            "to": 4,
          },
          {
            "duration": 3,
            "from": 4,
            "isManipulated": false,
            "time": 2,
            "to": 5,
          },
          {
            "duration": 4,
            "from": 5,
            "isManipulated": true,
            "time": 3,
            "to": 7,
          },
          {
            "duration": 3,
            "from": 4,
            "isManipulated": false,
            "time": 4,
            "to": 5,
          },
          {
            "duration": 3,
            "from": 5,
            "isManipulated": false,
            "time": 5,
            "to": 4,
          },
          {
            "duration": 3,
            "from": 4,
            "isManipulated": false,
            "time": 6,
            "to": 5,
          },
          {
            "duration": 2,
            "from": 1,
            "isManipulated": false,
            "time": 5,
            "to": 1,
          },
          {
            "duration": 1,
            "from": 7,
            "isManipulated": false,
            "time": 3,
            "to": 6,
          },
          {
            "duration": 1,
            "from": 6,
            "isManipulated": false,
            "time": 4,
            "to": 7,
          },
          {
            "duration": 1,
            "from": 7,
            "isManipulated": false,
            "time": 5,
            "to": 6,
          },
          {
            "duration": 1,
            "from": 6,
            "isManipulated": false,
            "time": 0,
            "to": 7,
          },
          {
            "duration": 4,
            "from": 7,
            "isManipulated": true,
            "time": 1,
            "to": 1,
          },
          {
            "duration": 1,
            "from": 6,
            "isManipulated": false,
            "time": 2,
            "to": 7,
          },
        ],
      }
    `);
  });
});
